FROM node:10

ENV POSTGRES_USERNAME=$POSTGRES_USERNAME \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_HOST=$POSTGRES_USERNAME \
    POSTGRES_DB=$POSTGRES_DB \
    AWS_BUCKET=$AWS_BUCKET \
    AWS_REGION=$AWS_REGION \
    AWS_PROFILE=$AWS_PROFILE \
    JWT_SECRET=$JWT_SECRET \
    URL=$URL \
    PORT=$PORT \
    ORIGIN_URL=$ORIGIN_URL

WORKDIR /home/node/app
COPY . .
RUN npm set cache .npm
RUN npm ci --only=production

EXPOSE 8081
CMD [ "node", "./www/server.js"]
